FROM python:3.12.3


ENV DEBIAN_FRONTEND=noninteractive


ENV POETRY_NO_INTERACTION=1 \
   POETRY_CACHE_DIR=/tmp/poetry_cache


RUN --mount=type=cache,target=~/.cache/pip pip install poetry && poetry config virtualenvs.create false


WORKDIR /app


RUN --mount=type=cache,target=~/.cache/pip pip install wheel Cython


COPY ./rl_string_helper ./rl_string_helper
RUN --mount=type=cache,target=~/.cache/pip pip3 install ./rl_string_helper


COPY ./database-lib ./database-lib
RUN --mount=type=cache,target=~/.cache/pip pip3 install ./database-lib


COPY ./medium-parser ./medium-parser
RUN --mount=type=cache,target=~/.cache/pip pip3 install ./medium-parser


COPY ./web ./web


WORKDIR /app/web


RUN --mount=type=cache,target=/tmp/poetry_cache poetry install --without dev --only main --no-ansi


# Install curl for healthchecks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*


# Create non-root user
RUN useradd -m freedium
USER freedium


# Expose port (Render.com will provide $PORT environment variable)
EXPOSE 7080


# Use shell form to allow environment variable expansion
# Render.com will provide $PORT, defaulting to 7080 if not set
CMD python3 -m server server --port ${PORT:-7080}